## Nodejs V18
FROM node:gallium-alpine

LABEL org.opencontainers.image.source https://github.com/nemrucloud/nodejs-expressjs

WORKDIR /app

RUN npm install -g npm@latest
RUN npm install -g nodemon

COPY entrypoint /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

ENTRYPOINT [ "/usr/bin/entrypoint" ]